[package]
name = "loam-cli"
description = "Loam CLI for building smart contracts"
homepage = "https://github.com/loambuild/loam-sdk"
repository = "https://github.com/loambuild/loam-sdk"
authors = ["Willem Wyndham <willem@ahalabs.dev>"]
license = "Apache-2.0"
readme = "../../README.md"
version = "0.8.0"
edition = "2021"
rust-version = "1.70"
autobins = false
default-run = "loam"

[[bin]]
name = "loam"
path = "src/bin/main.rs"

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-{ version }-{ target }{ archive-suffix }"
bin-dir = "{ bin }{ binary-ext }"


[lib]
name = "loam_cli"
path = "src/lib.rs"
doctest = false

[dependencies]
loam-build = { path = "../loam-build", version = "0.7.0" }
clap = { version = "4.1.8", features = [
    "derive",
    "env",
    "deprecated",
    "string",
] }

cargo_metadata = { workspace = true }
clap-cargo-extra = "0.3.0"

thiserror = "1.0.31"
serde = "1.0.82"
serde_derive = "1.0.82"
serde_json = "1.0.82"

tokio = { version = "1", features = ["full"] }
dirs = "5.0.1"
itertools = "0.12.1"
strsim = "0.11.1"
heck = "0.5.0"
pathdiff = "0.2.1"
shlex = "1.1.0"
symlink = "0.1.0"
toml = { version = "0.8.12", features = ["parse"] }
soroban-cli = { git = "https://github.com/AhaLabs/soroban-cli.git", rev = "8a24ff27c96d4b1244686798fc8f321ecdb7da5b" }

[dev-dependencies]
assert_cmd = "2.0.4"
assert_fs = "1.0.7"
fs_extra = "1.3.0"
predicates = "3.1.0"
