name: Build and publish npm package

# TODO: make this happen on release instead
on:
  workflow_dispatch:
    branches: main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "latest"
          registry-url: "https://registry.npmjs.org/"

      - name: Install dependencies
        run: npm install
        working-directory: npm/

      - name: Build the project
        run: npm run build
        working-directory: npm/

      - name: Publish package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish
        working-directory: npm/
